version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
    ports:
      - ${DB_PORT}:3306
    restart: "no"
    volumes:
      - ./romm_mock/database:/var/lib/mysql
    env_file:
      - .env